### ISSUE TITLE
“环游记”的入会参数1和2不起作用

### ISSUE THREAD

**Issue by LvDeShei** [shyyhs19625/Shy_yhS#3]
}if(IsJoinMember == null){
        IsJoinMember = 0 //0：不执行入会任务 1：执行入会任务，遇到新入会店铺则退出脚本 2：执行入会任务，遇到需入会店铺则返回，等待刷新别的店铺
    }

大佬，变量 IsJoinMember 参数设置为1和2都不起作用，启动脚本的提示还是“不执行入会”，辛苦了！

**Comment by shyyhs19625** [comment]
//京东例子
//Run("京东",0,0,2);home();
//Run("京东",1,1,0);home();

入会参数是设置这里
